### ISSUE TITLE
error: password authentication failed for user XXX

### ISSUE THREAD

**Issue by scheiblr** [SpringTree/pg-tables-to-jsonschema#2]
Hi,

as your tool looks quite interesting to me, I wanted to give it a try. Unfortunately, it crashes with the following error:
```
Fetching and parsing tables...
ERROR: Conversion failed { error: password authentication failed for user "XXX"
    at Connection.parseE (/home/schmittr/.node_modules_global/lib/node_modules/pg-tables-to-jsonschema/node_modules/pg.js/lib/connection.js:534:11)
    at Connection.parseMessage (/home/schmittr/.node_modules_global/lib/node_modules/pg-tables-to-jsonschema/node_modules/pg.js/lib/connection.js:361:17)
    at Socket.<anonymous> (/home/schmittr/.node_modules_global/lib/node_modules/pg-tables-to-jsonschema/node_modules/pg.js/lib/connection.js:105:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
  name: 'error',
  length: 105,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'auth.c',
  line: '307',
  routine: 'auth_failed' }
```

I tried it with 2 databases (remote and local) and checked if the connection is possible with `psql` which worked flawlessly. Do you have any idea why this happens? Both databases I tried to connect to postgres-server version 9.6.

Kind regards

**Comment by Qwerios** [comment]
Only thing that comes to mind is that if its a empty password you may need to supply it as `--pg-assword ''`

**Comment by scheiblr** [comment]
unfortunately this didn't work either..

**Comment by Qwerios** [comment]
Not having any issues with a similar call and I've been using this tool a lot lately

```
pgtables2jsonschema --pg-host localhost --pg-user mdoeswijk --pg-password '' --pg-database mydb --pg-schema myschema
```

I hate to say works on my machine but that appears to be the case :(

**Comment by scheiblr** [comment]
which npm version do you use and which OS?

**Comment by Qwerios** [comment]
Latest so 0.1.10 and I don't have newer local changes. OS is Mac 10.13.3

I've checked the passing of the password down the line to the library that does the actual postgresql stuff (https://github.com/tjwebb/pg-json-schema-export). And I'm seeing the password being passed along as expected.

**Comment by scheiblr** [comment]
did you compile it from source or installed it with npm -i ... ? Something must go wrong here on my machine.. ;)

**Comment by scheiblr** [comment]
hm, that's weird, I did `pgtables2jsonschema -V` and it says `0.0.1`

**Comment by Qwerios** [comment]
Well you found 1 bug the -V is broken on the cli. It's still hardcoded

**Comment by Qwerios** [comment]
Published 0.1.11 with the cli version fix

**Comment by Qwerios** [comment]
Installed packaged version. Still working here...

**Comment by Qwerios** [comment]
Best info I could find right now was this: https://github.com/brianc/node-postgres/issues/1080

Apparently PG on Mac OSX may have password checking disabled all together.

You could try running it with the password in ENV like so:

```
PGUSER=foo PGDATABASE=bar PGPASSWORD=baz pgtables2jsonschema  ....
```

**Comment by Qwerios** [comment]
Oh and this might be an obvious one but ensure your password does not contain bash shell expandable characters. I'm assuming you're putting the password in single quotes to prevent this.

**Comment by Qwerios** [comment]
I'm going to close this issue. Feel free to re-open it if you have more information

**Comment by Buttonsz** [comment]
I found out what may be causing this after having a similar problem. Seems like there's an error with using the pg.js package with knex if you use a newer node version - as stated here https://stackoverflow.com/questions/38111578/knexerror-pool2-error-password-authentication-failed-for-user - I've updated the pg.js to the pg npm package and now it's authenticating.

Hope that helps.

**Comment by Qwerios** [comment]
Thanks for the update and the fix @Buttonsz 

Glad it's working now @scheiblr
