### ISSUE TITLE
Feature request: export schema for single table

### ISSUE THREAD

**Issue by jasonkarns** [SpringTree/pg-tables-to-jsonschema#4]

**Comment by Qwerios** [comment]
I've added your requested feature in v0.2.0 which is now on NPM.

You can now use the new -t / --include-tables parameter to select any table you want
There is also a -e / --exclude-tables options to do the inverse

If you only want 1 table returned without it being in an array you can use the -u / --unwrap options just return the schema directly. I added this as an option for backwards compatibility.

Thanks for reporting your issues and I hope the software helps you.
